# SVM Classification

### This file has the final classification using SVM

1. The data consisting of 12 features is separated into train and test in the ratio 60:40. 
2. This data is scaled and fed into the SVM. 
3. The poly kernel for our algorithm was chosen because a linear kernel was not able to capture the complexity of the data. 
4. C is chosen to be 170 and it depicts how close to the margin are the data points. 
5. Once the SVM is trained, it is tested against the test set and parameters like accuracy and error rate are obtained.

Import dependencies

In [1]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np 
import os
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.svm import SVC
import sklearn
from sklearn.metrics import accuracy_score

Display the dataset

In [2]:
df = pd.read_excel(r'C:\Users\Kannan-PC\Desktop\MS\Projects\fall detection audios\Audio_Final_Data.xlsx')
df.dataframeName = 'Audio_Final_Data.csv'
df.head(5)

,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,Labels
0,0.0,0.0,0.0,37.25024,0.0,0.000000,0.354787,0.892783,1.383992,0.0,0.000000,4.241690,0.0
1,0.0,0.0,0.0,0.00000,0.0,0.025914,0.000000,0.815938,0.000000,0.0,2.243964,0.000000,0.0
2,0.0,0.0,0.0,0.00000,0.0,0.000000,0.145012,0.000000,0.000000,0.0,0.000000,0.000000,0.0
3,0.0,0.0,0.0,0.00000,0.0,0.189533,0.000000,0.000000,0.449374,0.0,0.000000,0.108856,0.0
4,0.0,0.0,0.0,14.15868,0.0,0.000000,0.000000,0.000000,0.000000,0.0,6.456151,0.262674,0.0

In [ ]:

X=df.iloc[:, 0:12]
y=df.iloc[:, -1:]
y=y.values
y=y.ravel()
print(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)
print(y_train)
print(X_train)

cols = X_train.columns

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])


svc= sklearn.svm.SVC (C=170.0, kernel='poly', degree=3, gamma='scale') 
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)

print('Model accuracy score with poly kernel and C=170.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))
print('Training set score: {:.4f}'.format(svc.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(svc.score(X_test, y_test)))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       31 non-null     object
 1   1       31 non-null     object
 2   2       31 non-null     object
 3   3       31 non-null     object
 4   4       31 non-null     object
 5   5       31 non-null     object
 6   6       31 non-null     object
 7   7       31 non-null     object
 8   8       31 non-null     object
 9   9       31 non-null     object
 10  10      31 non-null     object
 11  11      31 non-null     object
 12  12      31 non-null     object
dtypes: object(13)
memory usage: 3.3+ KB
['Labels' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
['0' '1' '1' '0' '1' '0' '0' '1' '1' '1' '0' '0' '1' '0' 'Labels' '1' '0'
 '0']
   0         1         2         3   ...        8         9         10        11
14  0         0         0  32.37643  ...  1.068986   0.40968         0         0
24  0         0         0  35.02646  ...  2.150559         0         0  1.874933
20  0         0         0         0  ...         0         0  1.341042  0.013617
1   0         0         0  37.25024  ...  1.383992         0         0   4.24169
30  0         0         0  53.92738  ...  0.021502         0         0         0
6   0         0         0         0  ...  0.472759         0   0.04497         0
4   0         0         0         0  ...  0.449374         0         0  0.108856
18  0         0         0         0  ...         0  1.596214  0.530121         0
28  0         0         0  43.69548  ...         0  1.918429  1.150395  1.437878
19  0         0         0  49.88633  ...   0.09085  1.120616  0.688714         0
9   0  35.41388         0  1.091682  ...         0  0.387516         0  0.261452
7   0   23.2788  13.06634  1.663964  ...         0  1.665984         0  0.204922
26  0         0         0         0  ...  0.354885  1.228895         0         0
3   0         0         0         0  ...         0         0         0         0
0   1         2         3         4  ...         9        10        11        12
21  0         0         0         0  ...         0  0.412216         0         0
15  0         0         0  29.73946  ...         0         0         0  0.115101
12  0  17.15432  12.74646  0.002604  ...         0  1.414138         0         0

[18 rows x 12 columns]
Model accuracy score with poly kernel and C=170.0 : 0.9231
Training set score: 0.9444
Test set score: 0.9231